export enum TileType {
	Empty,
	Rock,
	Door,
	SilverBar,
	Jetpack,
	BlueBrick,
	FireStart,
	TrophyStart = 10,
	PipeHorizontal = 15,
	PipeVertical,
	RedBrick,
	NormalRock,
	BlueWall,
	Gun,
	RockSlope1,
	RockSlope2,
	RockSlope3,
	RockSlope4,
	WeedStart,
	PurpleBarVertical = 29,
	PurpleBarHorizontal,
  TreeStart = 33,
  TreeEnd = 35,
	WaterStart,
  Stars = 41,
	BlueDiamond = 47,
	PurpleBall,
	RedDiamond,
	Crown,
	Ring,
	Wand,
	DaveRightStart,
  DaveDefault = 56,
	DaveLeftStart,
  DaveRightEnd = 59,
	DaveJumpRight = 67,
	DaveJumpLeft,
  DaveClimbStart = 71,
	DaveClimbEnd = 73,
	JetpackRightStart = 77,
	JetpackLeftStart = 80,
	JetpackLeftEnd = 82,
	MonsterSpiderStart = 89,
	MonsterPurpleThingStart = 93,
	MonsterRedSunStart = 97,
	MonsterGreenBarStart = 101,
	MonsterGreySaucerStart = 105,
	MonsterDoubleMushroomStart = 109,
	MonsterGreenCircleStart = 113,
	MonsterSilverSpinnerStart = 117,
	MonsterSilverSpinnerEnd = 120,
	MonsterBulletRight,
	MonsterBulletLeft = 124,
	DaveBulletRight = 127,
	DaveBulletLeft,
	ExplosionStart = 129,
  ExplosionEnd = 132,
  UIIconJetpack = 133,
  UIIconGun,
  UILivesBanner,
  UILevelBanner,
  UIScoreBanner,
  UIMessageTrophy,
  UIBarJetpack = 141,
  UIIconLife = 143,
	TitleStart = 144,
  UI0 = 148
}