export enum TileType {
	Door = 2,
	Jetpack = 4,
	Trophy = 10,
	Gun = 20,
  TreeStart = 33,
  TreeEnd = 35,
  Stars = 41,
	DaveRightStart = 53,
  DaveDefault = 56,
	DaveLeftStart,
  DaveRightEnd = 59,
	DaveJumpRight = 67,
	DaveJumpLeft,
  DaveClimbStart = 71,
	JetpackRight = 77,
	JetpackLeft = 80,
	MonsterSpider = 89,
	MonsterPurpleThing = 93,
	MonsterBulletRight = 121,
	MonsterBulletLeft = 124,
	DaveBulletRight = 127,
	DaveBulletLeft,
	ExplosionStart = 129,
  ExplosionEnd = 132,
  UIIconJetpack = 133,
  UIIconGun,
  UILivesBanner,
  UILevelBanner,
  UIScoreBanner,
  UIMessageTrophy,
  UIBarJetpack = 141,
  UIIconLife = 143,
  UI0 = 148
}
